image:
  file: .gitpod.Dockerfile

tasks:
  - name: NPM
    command: npm i -g npm@7 && gp sync-done npm

  - name: Deps
    before: gp sync-await npm
    command: npm i
github:
  prebuilds:
    addCheck: true
    branches: true
