name: Auto label Ready for QA

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  qa-review:
    runs-on: ubuntu-latest
    outputs:
      is-pending: ${{ steps.check-labels.outcome }}
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - run: echo "${{ github.event.review }}"

      - id: check-labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          none_of: QA-approved,QA-rejected
          all_of: Peer-reviewed
  logs:
    needs: qa-review
    runs-on: ubuntu-latest
    outputs:
      is-pending: ${{ steps.check-labels.outcome }}
    steps:
      - run: echo "${{ needs.qa-review.outputs.is-pending }}"

  ready-for-qa:
    needs: qa-review
    if: needs.qa-review.outputs.is-pending == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Ready for QA
