name: Automate PR reviews

on:
  pull_request_review:
    types: [submitted]

jobs:
  handle-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Add Peer-reviewed label when PR is approved
        if: github.event.review.state == 'approved'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Peer-reviewed

  handle-changes-requested:
    runs-on: ubuntu-latest
    steps:
      - name: Reset Peer-reviewed label if changes are requested
        if: github.event.review.state == 'changes_requested'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Peer-reviewed

      - name: Reset Ready for QA label if changes are requested
        if: github.event.review.state == 'changes_requested'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Ready for QA

      - name: Reset QA-approved label if changes are requested
        if: github.event.review.state == 'changes_requested'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: QA-approved

      - name: Reset QA-rejected label if changes are requested
        if: github.event.review.state == 'changes_requested'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: QA-rejected
