name: Automate PR sync

on:
  pull_request:
    types:
      - synchronize

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run: echo $commitmsg

      - name: step1
        if: contains( env.commitmsg , 'Merge master into' )
        run: echo hello

  handle-push:
    runs-on: ubuntu-latest
    outputs:
      is-ready: ${{ steps.check-labels.outcome }}
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.get-pr-commits.outputs.commits }}"

  dismiss-reviews:
    needs: handle-push
    if: needs.handle-push.outputs.is-ready == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Ready for QA
