name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: 'qa-approved, !DO NOT MERGE'
          MERGE_DELETE_BRANCH: true
