name: Auto update PR branch
on:
  push:
    branches: [master]

jobs:
  get-latest-commit:
    runs-on: ubuntu-latest
    outputs:
      message: echo "${{ steps.get-commit.outputs.message }}"
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 1
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - id: get-commit
        run: echo ::set-output name=push_commit_message::$(git log --format=%B -n 1 HEAD)

  log:
    needs: get-latest-commit
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.get-latest-commit.outputs.message}}"

  auto-update:
    needs: get-latest-commit
    if: "contains(needs.get-latest-commit.outputs.message, 'ci: version bump to')"
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
          PR_FILTER: 'labelled'
          PR_LABELS: 'ready-for-qa, qa-approved'
