name: Auto update branch
on:
  push:
    branches: [master]

jobs:
  auto-update:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_RUN }}
          PR_FILTER: 'labelled'
          PR_LABELS: 'Ready for QA'
