name: automerge
on:
  workflow_run:
    workflows: ['Test', 'CI']
    types: [completed]
    branches-ignore: ['master']
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN }}
          MERGE_LABELS: 'qa-approved, !DO NOT MERGE'
          MERGE_DELETE_BRANCH: true
