name: automerge
on:
  pull_request:
    types: [opened, ready_for_review, synchronize, labeled]
  pull_request_review:
    types: [submitted]
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.action == 'ready_for_review'
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: "SQUASH"
