name: Auto update branch
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - id: 'check-labels'
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'Ready for QA, QA Approved"'
      - uses: tibdex/auto-update@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
