name: Automate PR synchronize

on:
  pull_request:
    types: [synchronize]

jobs:
  dismiss-reviews:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, 'Merge') && contains(github.event.head_commit.message, 'master'))"
    steps:
      - name: Remove peer-approved label if changes are added
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}
          labels: peer-approved

      - name: Remove ready-for-qa label if changes are added
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}
          labels: ready-for-qa

      - name: Remove qa-approved label if changes are added
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}
          labels: qa-approved

      - name: Remove qa-rejected label if changes are added
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}
          labels: qa-rejected
