name: Automate PR sync

on:
  pull_request:
    types:
      - synchronize

jobs:
  initialise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # for pull_request so we can do HEAD^2
          fetch-depth: 2

      - name: Get commit message
        id: get_commit_message
        run: |
          echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD^2)
      - run: echo "${{ steps.get_commit_message.outputs.commit_message  }}"

    outputs:
      commit_message: echo "${{ steps.get_commit_message.outputs.commit_message }}"

  handle-push:
    runs-on: ubuntu-latest
    outputs:
      is-ready: ${{ steps.check-labels.outcome }}
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - run: echo "${{ steps.get-pr-commits.outputs.commits }}"

  dismiss-reviews:
    needs: handle-push
    if: needs.handle-push.outputs.is-ready == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Ready for QA
