name: Auto label Ready for QA

on:
  pull_request_review:
    types: [submitted]

jobs:
  qa-review:
    runs-on: ubuntu-latest
    outputs:
      is-pending: ${{ steps.check-labels.outcome }}
    steps:
      - id: check-labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          none_of: QA-approved,QA-rejected

  ready-for-qa:
    needs: qa-review
    if: github.event.review.state == 'approved' && needs.qa-review.outputs.is-pending == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Ready for QA
