name: 'Bump Version'

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'log'
        run: echo '${{ github.event_name }}'

      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.ADMIN }}

      - run: cat ./packages/a/package.json

      - name: 'Bump package a'
        id: version-bump-a
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: true
          push: false
          PACKAGEJSON_DIR: packages/a
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN }}

      - run: cat ./packages/a/package.json

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN }}

      - name: 'cat package.json'
        run: cat ./package.json
