name: 'Check Label'
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - id: 'check-qa-approval'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          none_of: 'QA Approved', 'QA Rejected'

      - name: View context attributes
        run: echo "${{ steps.check-qa-approval.outcome }}"
        