name: 'Check Label'
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - id: 'check-qa-approval'
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["QA Approved"]'

      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: |
            console.log('steps result', ${{ steps.check-qa-approval.outputs.result }})
            console.log('steps', JSON.stringify(${{ steps.check-qa-approval.outputs }}))
            console.log('context', context)
