name: 'Check Label'
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - id: 'check-qa-approval'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          one_of: 'QA Approved'

      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: |
            console.log('steps result', ${{ steps.check-qa-approval.outputs.result }})
            console.log('steps', JSON.stringify(${{ steps.check-qa-approval.outputs.result }}))
            console.log('context', context)
