name: 'Check Label'
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - id: 'check-qa-approval'
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          invalid-labels: 'QA Approved'
      - run: echo '${{ steps.check-qa-approval.outputs }}'
