name: Install Dependencies

on:
  push:
    branches: ['master']
  pull_request:
    branches: [master]

jobs:
  Install:
    runs-on: ubuntu-latest
    if: ${{  github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci

  Lint:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  Test:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
