name: Manually triggered workflow

on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"

      - uses: actions/checkout@v2
      - run: |
          cd packages/a && npm run test
