name: Pull Request Project Check

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

jobs:
  pr-project-check:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |

          echo "github.event.pull_request"
          echo "${{ toJson(github.event.pull_request) }}"
          echo ""
          echo "github.event.pull_request.has_projects"
          echo "${{ toJson(github.event.pull_request.has_projects) }}"
          echo ""
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The job context is:"
          echo "${{ toJson(job) }}"
          echo ""
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo ""
          echo "The runner context is:"
          echo "${{ toJson(runner) }}"
          echo ""
          echo "The strategy context is:"
          echo "${{ toJson(strategy) }}"
          echo ""
          echo "The matrix context is:"
          echo "${{ toJson(matrix) }}"

      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)

      - uses: actions/github-script@v4
        with:
          script: |
            const columns = await github.projects.listColumns({
              project_id: 13011876
            });

            console.log(columns)
