name: Handle PR or issue open

env:
  ORG_NAME: remo-co
  PROJECT_ID: 12876151
  PROJECT_NAME: Remo Engineering
  ISSUE_COLUMN_NAME: Backlog
  PR_COLUMN_NAME: In Progress

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  project-check:
    runs-on: ubuntu-latest
    steps:
      - uses: JulienKode/team-labeler-action@v0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
