name: Handle PR or issue open

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  project-check:
    runs-on: ubuntu-latest
    steps:
      - uses: JulienKode/team-labeler-action@v0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
