name: Pull Request Project Check

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

jobs:
  pr-project-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(JSON.stringify(${{github.event}}));
            console.log(JSON.stringify(${{github.event.pull_request}}));
            console.log(JSON.stringify(${{github.event.pull_request.has_projects}}));
