name: Record rejected PRs
on:
  pull_request:
    types: [labeled]

jobs:
  record-rejection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: worksheet
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const allowedLabels = ['QA Rejected', 'Ready for QA']
            console.log('label', context.payload.pull_request.labels)
            if (context.payload.pull_request.labels.find(({name}) => name === 'QA Rejected')) {
              return 'rejected'
            }
            if (context.payload.pull_request.labels.find(({name}) => name === 'Ready for QA')) {
              return 'reviewed'
            }
          result-encoding: string
      - uses: jroehl/gsheet.action@v1.0.0
        if: ${{ steps.worksheet.outputs.result !== undefined }}
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        with:
          spreadsheetId: 1pfh6CHEKdOhraRNQzxA5NDhE9jOtKqcC4f802Z-Dy9w

          commands: |
            [
              {
                "command": "appendData",
                "args": {
                  "data": [
                    [
                      "${{ github.event.pull_request.title }}",
                      "${{ github.event.pull_request.number }}",
                      "${{ github.event.pull_request.updated_at }}"
                      "${{ github.event.pull_request.html_url }}",
                    ]
                  ],
                  "minCol": 1,
                  "worksheetTitle": ${{steps.worksheet.outputs.result}}
                }
              }
            ]

      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
