name: Record rejected PRs
on:
  pull_request:
    branches: [master]
  issue_comment:
    types: [created]
jobs:
  record-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: approved
        with:
          trigger: '@qa-approved'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - id: 'record-approval'
        if: steps.approved.outputs.triggered == 'true'
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: 1pfh6CHEKdOhraRNQzxA5NDhE9jOtKqcC4f802Z-Dy9w
          commands: |
            [
              {
                "command": "appendData",
                "args": {
                  "data": [
                    [
                      "${{ github.event.pull_request.title }}",
                      "${{ github.event.pull_request.number }}",
                      "${{ github.event.pull_request.updated_at }}",
                      "${{ github.event.pull_request.html_url }}"
                    ]
                  ],
                  "minCol": 1,
                  "worksheetTitle": "approved"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
