name: Record rejected PRs
on:
  pull_request:
    types: [labeled]

jobs:
  record-rejection:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        id: setup
        run: |
          if contains(github.event.pull_request.labels.*.name, 'QA Rejected');
          then
              echo "::set-output name=worksheetTitle::rejected"
          elif contains(github.event.pull_request.labels.*.name, 'Ready for QA');
          then
              echo "::set-output name=worksheetTitle::reviewed"
          fi

      - name: record
        if: steps.setup.outputs.worksheetTitle
        uses: jroehl/gsheet.action@v1.0.0
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        with:
          spreadsheetId: 1pfh6CHEKdOhraRNQzxA5NDhE9jOtKqcC4f802Z-Dy9w
          worksheetTitle: steps.setup.outputs.worksheetTitle
          commands: |
            [
              {
                "command": "appendData",
                "args": {
                  "data": [
                    [
                      "${{ github.event.pull_request.title }}",
                      "${{ github.event.pull_request.number }}",
                      "${{ github.event.pull_request.updated_at }}"
                      "${{ github.event.pull_request.html_url }}",
                    ]
                  ],
                  "minCol": 1,
                  "worksheetTitle": "data"
                }
              }
            ]
