name: Record rejected PRs
on:
  pull_request:
    types: [labeled]

jobs:
  record-rejection:
    runs-on: ubuntu-latest
    steps:
      - if: contains( github.event.pull_request.labels.*.name, 'QA Rejected')
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: 1pfh6CHEKdOhraRNQzxA5NDhE9jOtKqcC4f802Z-Dy9w
          commands: |
            [
              {
                "command": "appendData",
                "args": {
                  "data": [
                    [
                      "${{ github.event.pull_request.title }}",
                      "${{ github.event.pull_request.number }}",
                      "${{ github.event.pull_request.updated_at }}"
                      "${{ github.event.pull_request.html_url }}",
                    ]
                  ],
                  "minCol": 1,
                  "worksheetTitle": "rejected"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - if: contains(github.event.pull_request.labels.*.name, 'Ready for QA')
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: 1pfh6CHEKdOhraRNQzxA5NDhE9jOtKqcC4f802Z-Dy9w
          commands: |
            [
              {
                "command": "appendData",
                "args": {
                  "data": [
                    [
                      "${{ github.event.pull_request.title }}",
                      "${{ github.event.pull_request.number }}",
                      "${{ github.event.pull_request.updated_at }}"
                      "${{ github.event.pull_request.html_url }}",
                    ]
                  ],
                  "minCol": 1,
                  "worksheetTitle": "reviewed"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
