name: Test

on:
  push:
    branches: ['master']
  pull_request:
    branches: [master]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['packages/a', 'packages/b']

    steps:
      - uses: actions/checkout@v2
      - run: cd ./${{ matrix.directory }} && npm ci
      - run: cd ./${{ matrix.directory }} && npm run test
      - id: package
        uses: actions/github-script@v3.1.0
        run: |
          core.setOutput('name', matrix.directory.slice(-1));
      - uses: actions/upload-artifact@v2
        with:
          name: unit-test-coverage
          path: ${{ matrix.directory }}/coverage-${{ steps.package.outputs.name }}

  Coverage:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: unit-test-coverage
