name: Test

on:
  push:
    branches: ['master']
  pull_request:
    branches: [master]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['packages/*']

    steps:
      - uses: actions/checkout@v2
      - run: cd ./${{ matrix.directory }}
      - run: npm ci
      - run: npm run test
