name: Lint

on:
  workflow_run:
    workflows: ['Install Dependencies']
    types:
      - completed

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['packages/a', 'packages/b']

    steps:
      - uses: actions/checkout@v2

      - run: npm run test
